defaults:
  - model: cnn_scratch
  - trainer: default
  - _self_

logger:
  wandb:
    project: "Proyecto-2"
    entity: "mauu-tec"
    log_model: true
    name: "default_run"

dataset:
  root: data
  class_name: ["bottle", "cable", "capsule", "grid", "pill", "screw", "tile", "toothbrush", "transistor", "zipper"]
  img_size: 224
  batch_size: 32
  num_classes: 10

train:
  lr: 1e-3
  epochs: 50
