defaults:
  - model: cnn_scratch
  - trainer: default
  - logger: wandb

dataset:
  root: data
  class_name: ["bottle", "cable", "capsule", "grid", "pill", "screw", "tile", "toothbrush", "transistor", "zipper"]
  img_size: 128
  batch_size: 32
  num_classes: 2

train:
  lr: 1e-3
  epochs: 50
